// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kijfwlnoczadpjthcevg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpamZ3bG5vY3phZHBqdGhjZXZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0MTY0MzUsImV4cCI6MjA1MTk5MjQzNX0.hRBBMlj_QprOSrhcpS7xFiTNKWh-RbmoZn2FupYdZoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);